config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root  'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  get 'ticker', to: 'tickers#show'
  get 'chart', to: 'charts#show'
  get 'table', to: 'tables#show'
  

resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base

belongs_to :user
validates :title, presence: true, length: {minimum: 3, maximum: 50}
validates :description, presence: true, length: {minimum: 10, maximum: 300}
validates :user_id, presence: true


end

app/models/user.rb
class User < ApplicationRecord

  has_many :articles
  before_save { self.email = email.downcase }
  validates :username, presence: true,

uniqueness: { case_sensitive: false },

length: { minimum: 3, maximum: 25 }

VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

validates :email, presence: true, length: { maximum: 105 },

uniqueness: { case_sensitive: false },

format: { with: VALID_EMAIL_REGEX }

has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def index
    @articles = Article.all
  end


  def new
    @article = Article.new

  end

  def edit

  @article = Article.find(params[:id])

  end





  def create


    @article = Article.new(article_params)
    @article.user = User.first
  if @article.save
    flash[:success] = "Post was successfully created"
    redirect_to article_path(@article)

  else
  render 'new'

  end
end

def update

@article = Article.find(params[:id])

if @article.update(article_params)

flash[:notice] = "Article was successfully updated"

redirect_to article_path(@article)

else

render 'edit'

end

end



def show

@article = Article.find(params[:id])

end

def destroy

@article.destroy
flash[:notice] = "Post was successfully deleted"
redirect_to articles_path
end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
  end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController

  def show

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home

end

def about

end



end

app/controllers/tables_controller.rb
class TablesController < ApplicationController

  def show

  end

end

app/controllers/tickers_controller.rb
class TickersController < ApplicationController

  def show

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

 @user = User.new

 end

 def create

 @user = User.new(user_params)

 if @user.save

 flash[:success] = "Welcome to CryptoNet #{@user.username}"

 redirect_to articles_path

 else

 render 'new'

 end

 end

 private

 def user_params

 params.require(:user).permit(  :username, :email, :password)

 end

 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<div class ="row">
<div class ="col-xs-8 col-xs-offset-2">
<div class ="panel panel-danger">
<div class ="panel-heading">
<h2 class = "panel-title">
  <%= pluralize(@article.errors.count, "error") %>
  prohibited this article from being saved:
</h2>
<div class = "panel-body">
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>

    <% end %>
  </ul>
</div>
</div>
</div>
</div>
</div>



<% end %>

<div class ="row">
  <div class ="col-xs-12">

<%=  form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
<div class = "form-group">
  <div class = "control-label col-sm-2">
  <%= f.label :title %>
</div>
<div class = "col-sm-8 ">
<%= f.text_field :title, class: "form-control", placeholder: "Title of post", autofocus: true  %>
</div>
</div>
<div class = "form-group">
  <div class = "control-label col-sm-2">

  <%= f.label :description  %>
</div>
<div class = "col-sm-8 ">
  <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of post", autofocus: true   %>
</div>
</div>

<div class = "form-group">
  <div class = "col-sm-offset-2 col-sm-10">
  <%= f.submit class: 'btn btn-primary btn-lg' %>
</div>
</div>


<% end %>

</div>
</div>

app/views/articles/edit.html.erb
<h1 align="center"> Edit </h1>
<%= render 'articles/form' %>

app/views/articles/index.html.erb
<h1 align="center"></h1>

<% @articles.each do |article| %>

<div class="row">

<div class="col-xs-8 col-xs-offset-2">

<div class="well well-lg">

<div class="article-title">

<%= link_to article.title, article_path(article) %>

</div>

<div class="article-body">

<%= truncate(article.description, length: 100) %>
<div class="article-meta-details">
<small>Created by: <%= article.user.username if article.user%>,
  <%= time_ago_in_words(article.created_at) %> ago,
   last updated: <%= time_ago_in_words(article.updated_at) %> ago
 </small>
</div>
</div>

<div class="article-actions">

<%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>

<%= link_to "Delete this article", article_path(article), method: :delete,

data: { confirm: "Are you sure you want to delete the article?"},

class: "btn btn-xs btn-danger" %>

</div>

</div>

</div>

</div>

<% end %>

app/views/articles/new.html.erb
<br>
<br>
<h1 align="center"> </h1>
<br>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>

<div class="well col-xs-8 col-xs-offset-2">

<h4 class="center description"><strong>Description:</strong></h4>

<hr>

<%= simple_format(@article.description) %>

<div class="article-actions">

<%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>

<%= link_to "Delete this article", article_path(@article), method: :delete,

data: { confirm: "Are you sure you want to delete the article?"},

class: "btn btn-xs btn-danger" %>

<%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>

</div>

</div>

app/views/charts/show.html.erb
<center><h1>Bitcoin Chart</h1></center>
<div class="container">


  <canvas id="Bitfinex"></canvas>
</div>


<script>
var buf = {};
buf['Bitfinex'] = [[], []];

var ws = new WebSocket('wss://api.bitfinex.com/ws/');
ws.onopen = function() {
    ws.send(JSON.stringify({
        "event": "subscribe",
        "channel": "trades",
        "pair": "BTCUSD"
    }));
};
ws.onmessage = function(msg) {
    var response = JSON.parse(msg.data);
    if (response[1] === 'te') {
        buf['Bitfinex'][response[5] > 0 ? 0 : 1].push({
            x: response[3] * 1000,
            y: response[4]
        });
    }
}
var id = 'Bitfinex';
var ctx = document.getElementById(id).getContext('2d');
var chart = new Chart(ctx, {
    type: 'line',
    data: {
        datasets: [{
            data: [],
            label: 'Buy',
            borderColor: 'rgb(255, 99, 132)',
            backgroundColor: 'rgba(255, 99, 132, 0.5)',
            fill: false,
            lineTension: 0
        }, {
            data: [],
            label: 'Sell',
            borderColor: 'rgb(54, 162, 235)',
            backgroundColor: 'rgba(54, 162, 235, 0.5)',
            fill: false,
            lineTension: 0
        }]
    },
    options: {
        title: {
            text: 'BTC/USD (' + id + ')',
            display: true
        },
        scales: {
            xAxes: [{
                type: 'realtime'
            }]
        },
        plugins: {
            streaming: {
                duration: 300000,
                onRefresh: function(chart) {
                    Array.prototype.push.apply(
                        chart.data.datasets[0].data, buf[id][0]
                    );
                    Array.prototype.push.apply(
                        chart.data.datasets[1].data, buf[id][1]
                    );
                    buf[id] = [[], []];
                }
            }
        }
    }
});



</script>

app/views/layouts/_footer.html.erb
<div class="container">

<footer >

<small>



</small>

<nav>

<ul>


</ul>

</nav>

</footer>

</div>

app/views/layouts/_messages.html.erb
<div class="row">

<div class="col-xs-10 col-xs-offset-1">

<% flash.each do |name, msg| %>

<div class='alert alert-<%="#{name}" %>'>

<a href="#" class="close" data-dismiss="alert">×</a>

<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>

</div>

<% end %>

</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kryptonet</title>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.js"></script>
    <script type="text/javascript" src="https://github.com/nagix/chartjs-plugin-streaming/releases/download/v1.1.0/chartjs-plugin-streaming.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pusher/4.1.0/pusher.js"></script>

  </head>

  <body>
    <div id ="background"> </div>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
    <%= yield %>
  </div>


  </body>
</html>

app/views/pages/about.html.erb
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<li> <%= link_to "Live Ticker", ticker_path %> </li>
<li> <%= link_to "Bitcoin Chart", chart_path %> </li>
<li> <%= link_to "Bitcoin Table", table_path %> </li>

app/views/shared/_errors.html.erb
<% if @article.errors.any? %>
<div class ="row">
<div class ="col-xs-8 col-xs-offset-2">
<div class ="panel panel-danger">
<div class ="panel-heading">
<h2 class = "panel-title">
  <%= pluralize(@article.errors.count, "error") %>
  prohibited this article from being saved:
</h2>
<div class = "panel-body">
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>

    <% end %>
  </ul>
</div>
</div>
</div>
</div>
</div>



<% end %>

app/views/tables/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <br>
      <h1 class="text-center">Bitcoin Price</h1>
      <br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3 col-md-offset-1 col-sm-4">
      <h2 class="text-center usd-price"></h2>
    </div>
    <div class="col-md-4">
      <h2 class="text-center gbp-price"></h2>
    </div>
    <div class="col-md-3 col-sm-4">
      <h2 class="text-center aud-price"></h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 prices"></div>
  </div>
</div>

app/views/tickers/show.html.erb
  <div id="ticker_window">
    <h1>BTC Ticker</h1>
    <center>  <table id="day_and_time"> </center>
      <tr>
        <td>
          <p id="date"></p>
        </td>
          <br>
        <td>
          <p id="clock"></p>
        </td>
      </tr>
    </table>
  <span class="exchange">&nbsp;Coinbase</span>
    <p class="status">Status: <span class="status" id="status">Connected</span></p></br>
    <div style="padding-left: 5px;">
      <ul id="ticker">
      </ul>
    </div>
  </div>